### ISSUE TITLE
Custom Agent Template Simplification Planning

### ISSUE THREAD

**Issue by LukeLalor** [eidolon-ai/eidolon#423]
I as a developer want to define agents/logic units in a familiar manner, similar to how I configure fastapi server or typer cli.

note that changes should be backward compatible with existing mechanism, perhaps with a "deprecated" warning on the existing mechanism pointing to the new pattern.

- [ ] propose new pattern
- [ ] implement said pattern
- [ ] update documentation around custom agents to point to pattern

See #723

**Comment by flynntsang** [comment]
Re: documentation updates, let's add known pages to update here.
- https://www.eidolonai.com/docs/howto/build_custom_agents
- https://www.eidolonai.com/docs/architecture/agent_program
- https://www.eidolonai.com/docs/architecture/agent_os
- https://www.eidolonai.com/docs/howto/using_references
