### ISSUE TITLE
sql agent Enhancements + Blog

### ISSUE THREAD

**Issue by LukeLalor** [eidolon-ai/eidolon#514]
Add SQLAgent to the docs and write a blog.

Enhancement -- create a separate issue.

**Comment by LukeLalor** [comment]
5 points since this covers work to 
1. Benchmark current agent in repeatable fashion (largely done)
2. Rearchitect to improve benchmarking
3. Write blog about process

**Comment by flynntsang** [comment]
I was thinking "recipes" for docs -- an example of how to use this bad boy.
