### ISSUE TITLE
Minor updates needed: git-search sample

### ISSUE THREAD

**Issue by flynntsang** [eidolon-ai/eidolon#619]
Issues: instructions for installing the git-search sample appear in both the documentation and the github README.md. The github readme appears out-of-date. 

Git repo is out of date: https://github.com/eidolon-ai/eidolon-git-search/blob/main/README.md
```
git clone https://github.com/eidolon-ai/**agent-git-search**.git
cd **agent-machine**
make **docker-serve**
```

Docs are correct: https://www.eidolonai.com/docs/recipes/repo-expert
```
git clone https://github.com/eidolon-ai/**eidolon-git-search**.git
cd **eidolon-git-search**
make **serve-dev**
```

Separately, when accessing "Explore Github Docs" from port 3000, the H1 agent name is incorrect. It references Venture Agent instead of Repo Expert.

![Image](https://github.com/user-attachments/assets/e536d698-fd5b-4b73-ab1e-0a921025f7c5)

**Comment by LukeLalor** [comment]
This is no longer an issue since our github example does not launch this config

**Comment by LukeLalor** [comment]
moving this to won't do since our examples no longer use this.

There is a relevant point around making an easy way to include a simplified chatbot interface for these examples, but that is a different item to prioritize all together.
