### ISSUE TITLE
Docs: APU application | agent processing unit

### ISSUE THREAD

**Issue by flynntsang** [eidolon-ai/eidolon#625]
The docs and blogs alternate between Application Processing Unit and Agent Processing Unit.

I find "Agent" Processing Unit more understandable.

**Comment by dbrewster** [comment]
It should be Agent. The others are typos DaveOn Aug 21, 2024, at 12:43 PM, flynntsang ***@***.***> wrote:﻿
The docs and blogs alternate between Application Processing Unit and Agent Processing Unit.
I find "Agent" Processing Unit more understandable.

**Comment by flynntsang** [comment]
I am using codespaces and selected the "Commit & Create Pull Request" drop down. It committed & pushed. Then it tried to create a PR, but the list of files was empty because it pushed the files already. 🤦 



![Image](https://github.com/user-attachments/assets/1238b294-513d-404f-9593-49c0e29563d5)
