### ISSUE TITLE
remote chromadb

### ISSUE THREAD

**Issue by LukeLalor** [eidolon-ai/eidolon#648]
We need to verify that we can run with a remote chroma db. This story captures that test work, and any code / documentation changes needed to make that work.

- [ ] Verify rag example ([s3 rag](https://github.com/eidolon-ai/eidolon-s3-rag) or [github](https://github.com/eidolon-ai/eidolon-git-search) work with a remote chromadb configuration

**Comment by LukeLalor** [comment]
Includes any doc changes that need to accompany the work

**Comment by flynntsang** [comment]
@LukeLalor reassisgn to Vibhav when he's added to the project

**Comment by LukeLalor** [comment]
Everything works! just config changes. Done by @vibhav, todo change assignee
