### ISSUE TITLE
Broken Docs Pages

### ISSUE THREAD

**Issue by jovanrlee** [eidolon-ai/eidolon#691]
https://www.eidolonai.com/docs/howto/customize_builtins
https://www.eidolonai.com/docs/components/simple_agent#defining-actions

**Comment by flynntsang** [comment]
Need to set redirects:
customize_builtins --> configure_builtins
custom_agents --> build_custom_agents.md

docs/components/simple_agent --> /docs/components/agents/simpleagent

**Comment by flynntsang** [comment]
@jovanrlee thank you for submitting issues!
