### ISSUE TITLE
[ problem ] Chatbot UI reverts to GPT-4 after each message

### ISSUE THREAD

**Issue by flynntsang** [eidolon-ai/eidolon#710]
This might be user error. This happens in developer tools. If this is expected behavior, we should document what developer tools is, why, and how it should be used.

**To Reproduce**
1. Clone [eidolon-chatbot](https://github.com/eidolon-ai/eidolon-chatbot/tree/main)
2. Add API_KEYS for Anthropic and Mistral to your `.env` file [docs](https://www.eidolonai.com/docs/howto/authenticate_llm)
3. Run `make docker-serve` (or `sudo make docker-serve`)
4. Go to the web UI -- DEVELOPER TOOLS -- and start a new chat with **conversational_agent**
5. Click the blue [ + ] button in the right corner to expand the input panel
6. Click a Claude or Mistral APU in the Execute on APU drop-down (you could also select GPT-3.5)
7. Type hello in the body

Notice that the APU reverts back to GPT-4 after your first message.

**Expected behavior**
If I change the APU it should keep the conversation on that APU.

**Comment by LukeLalor** [comment]
not a bug, dev tools should optimize non-generic around form behavior
