### ISSUE TITLE
Turning off "allow_file_upload" for an action in simple agent causes simple agent to always break (because the file upload field doesn't exist)

### ISSUE THREAD

**Issue by dbrewster** [eidolon-ai/eidolon#716]

**Comment by LukeLalor** [comment]
@dbrewster , what exactly is the problem, I just tried this locally through the the chatbot webui and it worked just fine

**Comment by dbrewster** [comment]
Set "allow_file_upload" to true on a nested agent (which is the default!). The agent doesn't pass a field which causes it to blow up.

I'm going to take this one as I have a fix locally for it.
