### ISSUE TITLE
[ polishing ]Quickstart

### ISSUE THREAD

**Issue by flynntsang** [eidolon-ai/eidolon#722]
[Quickstart](https://www.eidolonai.com/docs/quickstart)

- [x] include WebUI; make it one of two clients (web + cli) you can use
- [x] Open external links in a new tab (must use html, as markdown does not support this)
- [x] General updating with helpful info based on experience as a new user
- [x] Question for @LukeLalor or @dbrewster -- can we be more precise when we say "If the _server_ starts successfully..."? I changed it to "Eidolon" but are we really talking about the agent machine? Platform? What is the _server_?

[How to Authenticate With Your LLM](https://www.eidolonai.com/docs/howto/authenticate_llm)
- [x] Open external links in a new tab (must use html, as markdown does not support this)
- [x] General updating with helpful info based on experience as a new user
- [x] Question for @LukeLalor or @dbrewster -- do you need to restart Eidolon for changes to the `.env` file to take effect? If not I'll remove that from the bottom of the page

[How to Build Custom Agents](https://www.eidolonai.com/docs/howto/build_custom_agents)
- [x] Open external link in a new tab (Pydantic model)

[How to Use References](https://www.eidolonai.com/docs/howto/using_references)
- [x] Fixed broken links (no slash before docs in the link)
- [x] Open external link in a new tab (Pydantic model)

**Comment by LukeLalor** [comment]
@flynntsang , as for restarting eidolon and when you need to do it, it depends a lot on the environment you are doing it in.

For the quickstart running in docker, yes. For running in kubernetes, you would modify a kubernetes resource and then the change would take effect in the backgorund.

I think that our quickstart should go into a lot of detail about these things for the quickstart path (ie docker), but the other articles (like swapping your llm) can't be so precise and need to be more platform agnostic.

**Comment by LukeLalor** [comment]
server refers to the literal http server that you are running. It is distinguished from the webui, which I believe the user would also consider part of Eidolon, which is why Eidolon is probably a less precise term. 

In the template repos we are also calling it the agent machine, but if we are transitioning to calling this the agent server perhaps that verbiage should be updated to refer to agent server everywhere. It would start defining that term as well

**Comment by flynntsang** [comment]
Thanks -- I think the text is ok then. I'll convert it to a PR.
