### ISSUE TITLE
[ polishing ] update eidolon/v1 to support K8S

### ISSUE THREAD

**Issue by flynntsang** [eidolon-ai/eidolon#727]
All resource YAML files (and documentation of those files) that start with `apiVersion: eidolon/v1` need to change to `apiVersion: server.eidolonai.com/v1alpha1`. This is to support Kubernetes deployments.

To Do: search the repo for `apiVersion: eidolon/v1`. This should give you a list of files that need changing.

>![Image](https://github.com/user-attachments/assets/f47b1405-a10b-42fd-938b-57f765e575d4)

Question for @LukeLalor -- is there anything to know about making changes to forked repos, e.g., the quickstart?

**Comment by LukeLalor** [comment]
Let's skip the example repos in this ticket. They are hard for outside contributors to work with right now, and I can do that as I fix that
