### ISSUE TITLE
Server process terminates suddenly since 0.1.122

### ISSUE THREAD

**Issue by anoner0815** [eidolon-ai/eidolon#754]
Since docker.io/eidolonai/sdk_base:0.1.122 the server process just terminates after starting

``` 
eidolon@ec7e20f56032:/app/resources$ eidolon-server --disable-metrics DISBABLE_METRICS --fail-on-bad-agent false  -p 3001 .
INFO:     Started server process [166]
INFO:     Waiting for application startup.
INFO - Building machine 'DEFAULT'
``` 

No errors or anything.

The same behaviour is on K8s and Docker standalone.

I tested the versions up to 0.1.121 and they work, all version 0.1.122 <= 0.1.125 produce that probably wrong behaviour.

**Comment by LukeLalor** [comment]
thanks @anoner0815 

Was this one of our example repos? Or if it was a custom repository / branch could share that with us to reproduce the issue?

**Comment by anoner0815** [comment]
I was in the eidelon-git-search repo using just the Dockerfile and patching the EIDOLON_VERSION arg before building the image

**Comment by LukeLalor** [comment]
Ok, this is strange. eidolon-git-search works just fine for me, but when experimenting setting up azure I ran into the same issue. so I have a repro now.

Elevating and grabbing this since it is a pretty bad

**Comment by anoner0815** [comment]
I could reproduce this erroneous behaviour using `poetry run eidolon-server .` on eidolon-repo.

After checkout out a6c10cb3 (tag 0.1.121) the server stays up and running. Possibly an issue with WSL2?

**Comment by anoner0815** [comment]
System: 
- Ubuntu 22.04 in WSL2
- Local user
- Workspace is local, no mounted Win folder
- Python 3.10.12
- Poetry (version 1.8.3)
